export const workshopCopy = {
  zh: {
    title: '小熊的实验工坊。',
    intro: '一些还在折腾的小玩意。挑一个，让小熊开机试试。',
    eyebrow: 'PLAYBOOK / 08',
    bench: '小熊的实验工作台',
    replay: '让小熊再试一次',
    label: '工作台上的实验',
    choose: '选一个实验',
    back: '回到四个小故事',
    playbook: '逛逛 Playbook',
    footnote: '让网页里的小东西，有自己的生活。',
    idle: '螺丝刀、试验机，还有一点耐心。',
    loading: '小熊正在准备工具。',
    tightening: '先拧紧这颗小螺丝。',
    smoke: '咳……差一点。再调一下。',
    adjusting: '把旋钮轻轻转回来。',
    complete: '亮了。这次真的可以了。',
    static: '调试完成。小熊把成果放在这里。',
    failure: '小熊先休息一会儿，展品照常开放。',
    preview: '验收预览',
  },
  en: {
    title: 'The bear’s little workshop.',
    intro: 'A few small things, still being tinkered with. Pick one for a test run.',
    eyebrow: 'PLAYBOOK / 08',
    bench: 'The bear’s experimental workbench',
    replay: 'Ask the bear for another test run',
    label: 'ON THE WORKBENCH',
    choose: 'Choose an experiment',
    back: 'Back to four little stories',
    playbook: 'Explore Playbook',
    footnote: 'Giving small things on the web a life of their own.',
    idle: 'A screwdriver, a test rig, and a little patience.',
    loading: 'The bear is getting its tools ready.',
    tightening: 'First, tighten this little screw.',
    smoke: 'Ahem. Almost. One more adjustment.',
    adjusting: 'Turn the dial, just a little.',
    complete: 'It’s on. This time it really works.',
    static: 'All tuned up. The bear left the results here.',
    failure: 'The bear is resting. The exhibits are still open.',
    preview: 'Acceptance preview',
  },
} as const;

export const workshopProjects = [
  {
    id: 'living-scenes', number: '01',
    zh: {
      name: '生活场景', title: '一只熊的一天。',
      object: '选择小桌子，试运行生活场景实验',
      description: '让桌边的小熊有自己的作息：写代码、翻书、喝咖啡，也会在雨天撑伞。',
      detail: '时间与天气决定它的日常。碰一碰杯子、台灯或窗帘，它会给你一个小小的回应。',
      link: '走进生活场景展台',
    },
    en: {
      name: 'Living scenes', title: 'A day in a bear’s life.',
      object: 'Choose the miniature desk and test the living-scenes experiment',
      description: 'A desk bear with its own day: coding, reading, coffee, and an umbrella when it rains.',
      detail: 'Time and weather shape its routine. Try the mug, lamp, or curtain for a small response.',
      link: 'Visit the living-scenes exhibit',
    },
  },
  {
    id: 'reading-companion', number: '02',
    zh: {
      name: '阅读伙伴', title: '目光，跟着你走。',
      object: '选择书上的熊猫，试运行阅读伙伴实验',
      description: '一只安静的水墨熊猫，望向你正在看的地方，陪你把文章读完。',
      detail: '一整圈连续的目光，藏在一张图集里。移动鼠标，或在手机上点一点不同的方向。',
      link: '走进阅读伙伴展台',
    },
    en: {
      name: 'Reading companion', title: 'A gaze that follows you.',
      object: 'Choose the panda on the book and test the reading-companion experiment',
      description: 'A quiet watercolor panda looks toward what you are reading, keeping you company.',
      detail: 'A full circle of glances lives inside one atlas. Move your pointer, or tap a direction on your phone.',
      link: 'Visit the reading-companion exhibit',
    },
  },
] as const;
