export const newspaperCopy = {
  zh: {
    title: '保持来往',
    description: '新文章，偶尔来信。',
    unsubscribe: '随时可以退订。',
    email: '邮箱地址',
    subscribe: '寄给我',
    submitting: '正在订阅…',
    confirmed: '订阅成功，新文章会寄到你的邮箱。',
    already: '这个邮箱已经订阅过了，下期见。',
    rss: 'RSS 阅读',
    javascript: '邮件订阅需要启用 JavaScript，也可以通过下方的 RSS 链接阅读。',
    unavailable: '暂时未能完成订阅，请稍后重试。',
    invalidEmail: '请检查邮箱地址，然后重试。',
    limited: '请求有些频繁，请稍后再试。',
    network: '连接中断，尚未确认订阅结果。请稍后重试。',
  },
  en: {
    title: 'Keep in touch',
    description: 'New stories, occasional letters.',
    unsubscribe: 'Unsubscribe anytime.',
    email: 'Email address',
    subscribe: 'Write to me',
    submitting: 'Subscribing…',
    confirmed: 'You’re subscribed. The next article will arrive in your inbox.',
    already: 'This email is already subscribed. Until next time.',
    rss: 'Read via RSS',
    javascript: 'Enable JavaScript for email subscriptions, or use the RSS link below.',
    unavailable: 'We couldn’t complete your subscription. Please try again later.',
    invalidEmail: 'Please check your email address and try again.',
    limited: 'Too many requests. Please try again later.',
    network: 'The connection was interrupted, so we couldn’t confirm your subscription. Please try again.',
  },
} as const;
